services:
  app:
    build: .
    ports:
      - "5000:5000"
    environment:
      - DATABASE_URL=postgresql
    depends_on:
      - db

  db:
    image: postgres:16
    environment:
      POSTRGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTRGRES_DB: mydatabase
    ports:
      - "5432:5432"